### ISSUE TITLE
To-Do-List for Browser in prep of Landing Page

### ISSUE THREAD

**Issue by DylanMoriarty** [hotosm/oam-browser#156]
Here is a checklist of the tasks we need to hit on the browser before launching an OAM landing page:

- [x] Remove landing modal
- [x] Add 'view latest imagery' functionality
- [x] Link back to the landing page (The logo at top seems to be a logical choice)
- [x] Create a similar link back to the landing page from the OAM Status tool. Would be nice to have a 'back' link to return to the map as well from that page.

This isn't as crucial, but we should also hit this up before an 'official/_publicized launch_' for consistency.

- [x] Tweak and simplify text in the 'about' modal. Add link out to the a more detailed 'about' page. (#149)

**Comment by DylanMoriarty** [comment]
Checklist complete. New landing page is being reviewed over in PR #158.
